=head1 NAME

pipicpowerd -  monitor and control Raspberry Pi power supply with i2c

=head1 SYNOPSIS

B<pipicpowerd> [B<-h>] [B<-v>] [B<-V>]

=head1 DESCRIPTION

The B<pipicpowerd> is used to monitor and control Raspberry Pi power supply
with i2c bus.

=head1 OPTIONS

B<-h> display a short help text

B<-v> verbose

B<-V> print version

=head1 FILES

I</etc/logrotate.d/pipicpowerd>    Log rotation configuration file.

I</etc/init.d/pipicpowerd>         Init script.

I</var/log/pipicpowerd.log>        Log file.

=head1 WARNING

No check is done where the query data is written. Could make some hardware 
unusable.

=head1 AUTHORS

Jaakko Koivuniemi 

=head1 SEE ALSO

pipic(1), pipicfile(1), i2cdetect(8), i2cset(8), i2cget(8)

