#!/bin/sh
#
# Installation script for Rasbian Wheezy. The installation script can be
# run after compiling the binaries.
#
# 'pipicpowerd' installation:
#
# a) cd src; make
# 
# b) cd doc/man; ./mkman
# 
# c) sudo ./install (this script)
#
# d) sudo raspi-config (to enable I2C) 
#
# e) add line 'dtparam=i2c=on,i2c_baudrate=10000' to /boot/config.txt
#
# f) sudo pipic -a 26 -c 50 (or set FORCERESET from configuration file)
#
# g) sudo service pipicpowerd start
# 
# h) tail -f /var/log/daemon.log
#
# i) sudo update-rc.d pipicpowerd defaults (optional)
#
# Similar way for the daemons 'pipicswd' and 'pipichbd'. 
#
# The directories used and files created by this script:
#
# /etc/init.d/pipichbd               - H-bridge init script
# /etc/init.d/pipicpowerd            - power supply init script
# /etc/init.d/pipicswd               - power switch init script
# /etc/pipichbdd_config              - H-bridge configuration file
# /etc/pipicpowerd_config            - power supply configuration file
# /etc/pipicswd_config               - power switch configuration file
# /usr/share/man                     - manual pages
# /usr/sbin/pipic                    - read and control PiPIC
# /usr/sbin/pipicfile                - print files from PiPIC
# /usr/sbin/pipichbd                 - H-bridge daemon
# /usb/sbin/pipichb                  - H-bridge client
# /usr/sbin/pipicpowerd              - power supply daemon
# /usr/sbin/pipicswd                 - power switch daemon
# /usr/sbin/pipicsw                  - power switch client
# /usr/sbin/pipictest                - send and read test data from PiPIC 
#
# Wed May 14 21:59:43 CEST 2014
# Edit: Sun Apr 19 14:42:22 CEST 2015
# 
# Jaakko Koivuniemi
#

# source directory for 'PiPIC'
SOURCEDIR=${PWD}
SOURCEBIN=${SOURCEDIR}/src
SOURCEMAN=${SOURCEDIR}/doc/man

# binary executables 
BINDIR=/usr/sbin

# manual pages
MANDIR=/usr/share/man/man1

# init script
INITDIR=/etc/init.d

# for pipicpowerd_conf configuration file
CONFDIR=/etc

# live data 
VARLIBDIR=/var/lib

# binary executables
BINS='pipic pipicfile pipichbd pipicpowerd pipicsw pipicswd pipictest'

if [ -d $SOURCEBIN ]; then
  echo "Copy binary executables to ${BINDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEBIN}/${item} ]; then
       echo "... ${item}"
       /usr/bin/install -C -m 755 ${SOURCEBIN}/${item} ${BINDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEBIN} does not exist"
fi

if [ -d $SOURCEMAN ]; then
  echo "Copy manual pages to ${MANDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEMAN}/$item.1 ]; then
       echo "... ${item}.1"
       /usr/bin/install -C -m 664 ${SOURCEMAN}/${item}.1 ${MANDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEMAN} does not exist"
fi

if [ ! -x ${INITDIR}/pipicpowerd ]; then
  echo "Write init script ${INITDIR}/pipicpowerd"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/pipicpowerd/pipicpowerd.sh ${INITDIR} 
  /bin/mv ${INITDIR}/pipicpowerd.sh ${INITDIR}/pipicpowerd
else
  echo "Init script ${INITDIR}/pipicpowerd already exists"
fi

if [ ! -r ${CONFDIR}/pipicpowerd_config ]; then
  echo "Write default configuration file ${CONFDIR}/pipicpowerd_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/pipicpowerd/pipicpowerd_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/pipicpowerd.config already exists" 
fi

if [ ! -x ${INITDIR}/pipicswd ]; then
  echo "Write init script ${INITDIR}/pipicswd"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/pipicswd/pipicswd.sh ${INITDIR} 
  /bin/mv ${INITDIR}/pipicswd.sh ${INITDIR}/pipicswd
else
  echo "Init script ${INITDIR}/pipicswd already exists"
fi

if [ ! -r ${CONFDIR}/pipicswd_config ]; then
  echo "Write default configuration file ${CONFDIR}/pipicswd_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/pipicswd/pipicswd_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/pipicswd.config already exists" 
fi

if [ ! -x ${INITDIR}/pipichbd ]; then
  echo "Write init script ${INITDIR}/pipichbd"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/pipichbd/pipichbd.sh ${INITDIR} 
  /bin/mv ${INITDIR}/pipichbd.sh ${INITDIR}/pipichbd
else
  echo "Init script ${INITDIR}/pipichbd already exists"
fi

if [ ! -r ${CONFDIR}/pipichbd_config ]; then
  echo "Write default configuration file ${CONFDIR}/pipichbd_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/pipichbd/pipichbd_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/pipichbd.config already exists" 
fi

if [ -d /var/lib/pipicpowerd ]; then
  echo "Directory to /var/lib/pipicpowerd already exists"
else
  echo "Create directory /var/lib/pipicpowerd"
  /bin/mkdir -m 775 /var/lib/pipicpowerd
fi

if /bin/grep -Fxq "i2c-bcm2708" /etc/modules
then
  echo "i2c-bcm2708 found from /etc/modules"
else
  echo "Add i2c-bcm2708 to /etc/modules"
  echo "i2c-bcm2708" >> /etc/modules
fi

if /bin/grep -Fxq "i2c-dev" /etc/modules
then
  echo "i2c-dev found from /etc/modules"
else
  echo "Add i2c-dev to /etc/modules"
  echo "i2c-dev" >> /etc/modules
fi

echo "Run 'update-rc.d pipicpowerd defaults' to automatically start at boot time"
