#!/bin/sh
#
# Installation script for Raspbian Buster. The installation script can be
# run after compiling the binaries.
#
# 'pipicpowerd' installation:
#
# a) cd src; make
# 
# b) cd doc/man; ./mkman
# 
# c) sudo ./install (this script)
#
# d) sudo raspi-config (to enable I2C) 
#
# e) add line 'dtparam=i2c_arm=on,i2c_arm_baudrate=10000' to /boot/config.txt (10 kHz I2C clock)
#
# f) sudo pipic -a 26 -c 50 (or set FORCERESET from configuration file)
#
# g) sudo systemctl start pipicpowerd.service
# 
# h) journalctl -u pipicpowerd.service --follow -p info
#
# i) sudo systemctl enable pipicpowerd.service (optional)
#
# Similar way for the daemons 'pipicswd' and 'pipichbd'. 
#
# The directories used and files created by this script:
#
# /etc/pipichbdd_config              - H-bridge configuration file
# /etc/pipicpowerd_config            - power supply configuration file
# /etc/pipicswd_config               - power switch configuration file
# /usr/share/man                     - manual pages
# /lib/systemd/system/pipicpowerd.service - service unit file
# /usr/local/bin/pipic               - read and control PiPIC
# /usr/local/bin/pipicfile           - print files from PiPIC
# /usr/local/bin/pipichbd            - H-bridge daemon
# /usb/local/bin/pipichb             - H-bridge client
# /usr/local/bin/pipicpowerd         - power supply daemon
# /usr/local/bin/pipicswd            - power switch daemon
# /usr/local/bin/pipicsw             - power switch client
# /usr/local/bin/pipictest           - send and read test data from PiPIC 
#
# Wed May 14 21:59:43 CEST 2014
# Edit: Mon 28 Dec 2020 05:51:48 PM CST
# 
# Jaakko Koivuniemi
#

# source directory for 'PiPIC'
SOURCEDIR=${PWD}
SOURCEBIN=${SOURCEDIR}/src
SOURCEMAN=${SOURCEDIR}/doc/man

# binary executables 
BINDIR=/usr/local/bin

# manual pages
MANDIR=/usr/share/man/man1

# systemd unit configuration file 
UNITCONF=/lib/systemd/system

# for pipicpowerd_conf configuration file
CONFDIR=/etc

# live data 
VARLIBDIR=/var/lib

# binary executables
BINS='pipic pipicfile pipichbd pipicpowerd pipicsw pipicswd pipictest'

if [ -d $SOURCEBIN ]; then
  echo "Copy binary executables to ${BINDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEBIN}/${item} ]; then
       echo "... ${item}"
       /usr/bin/install -C -m 755 ${SOURCEBIN}/${item} ${BINDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEBIN} does not exist"
fi

if [ -d $SOURCEMAN ]; then
  echo "Copy manual pages to ${MANDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEMAN}/$item.1 ]; then
       echo "... ${item}.1"
       /usr/bin/install -C -m 664 ${SOURCEMAN}/${item}.1 ${MANDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEMAN} does not exist"
fi

if [ ! -r ${UNITCONF}/pipicpowerd.service ]; then
  echo "Write systemd unit configuration file ${UNITCONF}/pipicpowerd.service"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/pipicpowerd/pipicpowerd.service ${UNITCONF} 
else
  echo "Unit file ${UNITCONF}/pipicpowerd.service already exists"
fi

if [ ! -r ${CONFDIR}/pipicpowerd_config ]; then
  echo "Write default configuration file ${CONFDIR}/pipicpowerd_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/pipicpowerd/pipicpowerd_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/pipicpowerd.config already exists" 
fi

if [ ! -r ${UNITCONF}/pipicswd.service ]; then
  echo "Write systemd unit configuration file ${UNITCONF}/pipicswd.service"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/pipicswd/pipicswd.service ${UNITCONF} 
else
  echo "Unit file ${UNITCONF}/pipicswd.service already exists"
fi

if [ ! -r ${CONFDIR}/pipicswd_config ]; then
  echo "Write default configuration file ${CONFDIR}/pipicswd_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/pipicswd/pipicswd_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/pipicswd.config already exists" 
fi

if [ ! -r ${UNITCONF}/pipichbd.service ]; then
  echo "Write systemd unit configuration file ${UNITCONF}/pipichbd.service"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/pipichbd/pipichbd.service ${UNITCONF} 
else
  echo "Unit file ${UNITCONF}/pipichbd.service already exists"
fi

if [ ! -r ${CONFDIR}/pipichbd_config ]; then
  echo "Write default configuration file ${CONFDIR}/pipichbd_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/pipichbd/pipichbd_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/pipichbd.config already exists" 
fi

if [ -d /var/lib/pipicpowerd ]; then
  echo "Directory to /var/lib/pipicpowerd already exists"
else
  echo "Create directory /var/lib/pipicpowerd"
  /bin/mkdir -m 775 /var/lib/pipicpowerd
fi

if /bin/grep -Fxq "i2c-bcm2708" /etc/modules
then
  echo "i2c-bcm2708 found from /etc/modules"
else
  echo "Add i2c-bcm2708 to /etc/modules"
  echo "i2c-bcm2708" >> /etc/modules
fi

if /bin/grep -Fxq "i2c-dev" /etc/modules
then
  echo "i2c-dev found from /etc/modules"
else
  echo "Add i2c-dev to /etc/modules"
  echo "i2c-dev" >> /etc/modules
fi

