=head1 NAME

pipicswd -  monitor and control Raspberry Pi power switch with i2c

=head1 SYNOPSIS

B<pipicswd> 

=head1 DESCRIPTION

The B<pipicswd> is used to monitor and control Raspberry Pi power switch 
with i2c bus. The daemon is started with command 

B<service> I<pipicswd> I<start>

and can be stopped any time with

B<service> I<pipicswd> I<stop>

The operation of the daemon can be checked from the log file.
At the start four test bytes are written to the switch and read back.
If this data flow test fails the daemon exits. One reason for this
failure could be that the internal counter of PIC was not yet reset with
command B<pipic> B<-a> 27 B<-c> 50.

In the main loop a socket is listened for any incoming commands. The possible
commands are

I<status> send switch status to the connecting client

I<close> I<N> I<[HH:MM]> close switch with channel number I<N>, time optional

I<open> I<N> I<[HH:MM]> open switch with channel number I<N>, time optional

I<cancel> I<N> stop timer I<N> command
 
=head1 FILES

I</etc/logrotate.d/pipicswd>       Log rotation configuration file.

I</etc/init.d/pipicswd>            Init script.

I</etc/pipicswd_config>            Configuration file.

I</usr/sbin/pipicswd>              Daemon code.

I</var/log/pipicswd.log>           Log file.

I</var/run/pipicswd.pid>           PID file.

=head1 WARNING

No check is done where the query data is written. Could make some hardware 
unusable.

=head1 AUTHORS

Jaakko Koivuniemi 

=head1 SEE ALSO

pipicsw(1), pipic(1), pipicfile(1), pipictest(1), socket(2)

