#!/usr/bin/perl -w
#
# Read pipicpowerd.log and extract battery data from it.
# Usage: filterlog < file
#

use strict;

my $line="";
my $volts=0.0;
my $cap=0.0;
my $hours=0.0;
my $temp=0.0;

print "time                 voltint  volts[V] cap[%] hours-empty temp[C]\n";

$line=<>;
while($line) 
{
    printf "%4d-%02d-%02d %02d:%02d:%02d   %03d      %4.1f  %3.0f  %3.0f   %4.1f\n",$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 if($line =~ /(\d{4})-(\d{2})-(\d{2})\s(\d{2}):(\d{2}):(\d{2})\s+read\svoltage\s(\d{1,4})\s\((\d{1,2}\.\d)\s+(\d{1,3})\s+hours\sat\s(\d{1,2}\.\d)\ C\).*/);

if($line =~ /(\d{4})-(\d{2})-(\d{2})\s(\d{2}):(\d{2}):(\d{2})\s+read\svoltage\s(\d{1,4})\s\((\d{1,2}\.\d)\sV\s+(\d{1,3})\s\%\s+(\d{1,3})\shours\sat\s(\d{1,2}\.\d).*/)
  {
    $volts=1.0*$8;
    $cap=1.0*$9;
    $hours=1.0*$10;
    $temp=1.0*$11;
    printf "%4d-%02d-%02d %02d:%02d:%02d  %03d      %4.1f    %3.0f    %3.0f          %4.1f\n",$1,$2,$3,$4,$5,$6,$7,$volts,$cap,$hours,$temp; 
  }
    $line=<>;
}


